(() => {
  const style = document.createElement('style');
  style.textContent = `.sp-support{position:fixed;right:20px;bottom:20px;z-index:1000;font:15px system-ui;color:#e2e8f0}.sp-launch,.sp-support button{cursor:pointer;background:#4f46e5;color:white;border:0;border-radius:12px;padding:10px 14px}.sp-panel{width:min(370px,calc(100vw - 24px));height:min(520px,calc(100dvh - 100px));background:#0f172a;border:1px solid #475569;border-radius:18px;box-shadow:0 12px 45px #0008;display:flex;flex-direction:column;overflow:hidden;margin-bottom:12px}.sp-panel[hidden]{display:none}.sp-head{display:flex;justify-content:space-between;align-items:center;padding:14px;background:#1e293b}.sp-log{flex:1;overflow:auto;padding:14px}.sp-msg{white-space:pre-wrap;overflow-wrap:anywhere;padding:10px;margin:8px 0;background:#1e293b;border-radius:12px}.sp-user{background:#3730a3}.sp-quick{display:flex;gap:5px;padding:8px;flex-wrap:wrap}.sp-quick button{font-size:12px;padding:7px}.sp-form{display:flex;gap:8px;padding:12px}.sp-form input{min-width:0;flex:1;background:#1e293b;color:white;border:1px solid #64748b;border-radius:10px;padding:10px}.sp-note{font-size:11px;padding:0 12px 10px;color:#94a3b8}`;
  document.head.append(style);
  const root = document.createElement('div'); root.className='sp-support';
  root.innerHTML='<section class="sp-panel" hidden role="region" aria-label="StreamPulse 客服"><header class="sp-head"><strong>💬 StreamPulse 客服</strong><button type="button" aria-label="縮小客服">−</button></header><div class="sp-log" role="log" aria-live="polite"></div><div class="sp-quick"><button type="button">登入問題</button><button type="button">播放問題</button><button type="button">我的影音庫</button></div><form class="sp-form"><input aria-label="客服問題" placeholder="輸入問題…" maxlength="1000" required><button type="submit">傳送</button></form><div class="sp-note">請勿輸入密碼或付款資料。AI 回覆可能有誤。</div></section><button class="sp-launch" type="button" aria-expanded="false">💬 客服</button>';
  document.body.append(root);
  const panel=root.querySelector('.sp-panel'), launch=root.querySelector('.sp-launch'), log=root.querySelector('.sp-log'), form=root.querySelector('form'), input=root.querySelector('input'), send=form.querySelector('button');
  let welcomed=false, busy=false; const history=[];
  function message(text,user=false){const el=document.createElement('div');el.className='sp-msg'+(user?' sp-user':'');el.textContent=text;log.append(el);log.scrollTop=log.scrollHeight;}
  function close(){panel.hidden=true;launch.setAttribute('aria-expanded','false');launch.focus();}
  launch.onclick=()=>{if(!panel.hidden){close();return;}panel.hidden=false;launch.setAttribute('aria-expanded','true');if(!welcomed){let name='';try{name=currentUser?.name||'';}catch{}message(`${name ? name+'，' : ''}你好！歡迎來到 StreamPulse。可以詢問登入、播放及影音庫使用方式。`);welcomed=true;}input.focus();};
  root.querySelector('.sp-head button').onclick=close;root.addEventListener('keydown',e=>{if(e.key==='Escape')close();});
  const faq=[[/登入|login|ログイン/i,'請使用網站上方的登入按鈕。若 Google 登入失敗，請記下畫面錯誤並提供給管理員；客服不會索取密碼。'],[/播放|play|再生/i,'請先手動點播放，檢查音量及來源連結。若出現錯誤，請提供影片標題與錯誤訊息，勿重複購買方案。'],[/影音庫|收藏|清單/i,'在影音卡片使用收藏或加入清單功能，再到「我的影音庫」查看。若清單未同步，請確認使用相同帳號登入。'],[/上傳|upload/i,'這是觀眾頁面。上傳問題需要由創作者或管理員在管理端確認；請提供錯誤訊息，客服無法直接修改儲存設定。']];
  async function ask(text){if(busy||!text.trim())return;message(text,true);input.value='';const match=faq.find(([pattern])=>pattern.test(text));if(match){message(match[1]);return;}const endpoint=window.STREAMPULSE_SUPPORT_API;if(!endpoint){message('目前提供常見問題自動回覆。AI 客服尚未連接後端，請選擇快捷問題或聯絡網站管理員。');return;}busy=true;send.disabled=true;const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),25000);try{const response=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:text,history:history.slice(-8)}),signal:controller.signal});const data=await response.json();if(!response.ok)throw new Error(data.error||'客服暫時無法回覆（'+response.status+'）');if(typeof data.reply!=='string')throw new Error('客服回應格式錯誤');message(data.reply);history.push({role:'user',content:text},{role:'assistant',content:data.reply.slice(0,4000)});history.splice(0,Math.max(0,history.length-8));}catch(e){message(e.name==='AbortError'?'客服回覆逾時，請稍後再試。':e.message);}finally{clearTimeout(timer);busy=false;send.disabled=false;}}
  form.onsubmit=e=>{e.preventDefault();ask(input.value.trim());};root.querySelectorAll('.sp-quick button').forEach(b=>b.onclick=()=>ask(b.textContent));
})();
